<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $patients = [
            [
                'name' => 'Muhammad Ali',
                'gender' => 'male',
                'age' => 45,
                'phone' => '0321-1234567',
                'marital_status' => 'married',
                'present_address' => 'House 123, Street 5, Gulberg, Lahore',
                'permanent_address' => 'House 123, Street 5, Gulberg, Lahore',
                'emergency_name' => 'Ayesha Ali',
                'emergency_phone' => '0321-1234568',
                'emergency_relation' => 'Wife',
            ],
            [
                'name' => 'Fatima Khan',
                'gender' => 'female',
                'age' => 32,
                'phone' => '0322-2345678',
                'marital_status' => 'married',
                'present_address' => 'Flat 45, DHA Phase 5, Karachi',
                'permanent_address' => 'Flat 45, DHA Phase 5, Karachi',
                'emergency_name' => 'Ahmed Khan',
                'emergency_phone' => '0322-2345679',
                'emergency_relation' => 'Husband',
            ],
            [
                'name' => 'Hassan Ahmed',
                'gender' => 'male',
                'age' => 28,
                'phone' => '0323-3456789',
                'marital_status' => 'single',
                'present_address' => 'House 67, F-7, Islamabad',
                'permanent_address' => 'House 67, F-7, Islamabad',
                'emergency_name' => 'Sadia Ahmed',
                'emergency_phone' => '0323-3456790',
                'emergency_relation' => 'Mother',
            ],
            [
                'name' => 'Ayesha Malik',
                'gender' => 'female',
                'age' => 55,
                'phone' => '0324-4567890',
                'marital_status' => 'married',
                'present_address' => 'House 89, Johar Town, Lahore',
                'permanent_address' => 'House 89, Johar Town, Lahore',
                'emergency_name' => 'Usman Malik',
                'emergency_phone' => '0324-4567891',
                'emergency_relation' => 'Son',
            ],
            [
                'name' => 'Zain Abbas',
                'gender' => 'male',
                'age' => 8,
                'phone' => '0325-5678901',
                'marital_status' => 'single',
                'present_address' => 'House 12, Model Town, Lahore',
                'permanent_address' => 'House 12, Model Town, Lahore',
                'emergency_name' => 'Sara Abbas',
                'emergency_phone' => '0325-5678902',
                'emergency_relation' => 'Mother',
            ],
            [
                'name' => 'Sana Tariq',
                'gender' => 'female',
                'age' => 26,
                'phone' => '0326-6789012',
                'marital_status' => 'single',
                'present_address' => 'Flat 23, Clifton, Karachi',
                'permanent_address' => 'Flat 23, Clifton, Karachi',
                'emergency_name' => 'Tariq Mahmood',
                'emergency_phone' => '0326-6789013',
                'emergency_relation' => 'Father',
            ],
            [
                'name' => 'Ahmed Raza',
                'gender' => 'male',
                'age' => 62,
                'phone' => '0327-7890123',
                'marital_status' => 'married',
                'present_address' => 'House 45, Satellite Town, Rawalpindi',
                'permanent_address' => 'House 45, Satellite Town, Rawalpindi',
                'emergency_name' => 'Nazia Raza',
                'emergency_phone' => '0327-7890124',
                'emergency_relation' => 'Wife',
            ],
            [
                'name' => 'Maria Hassan',
                'gender' => 'female',
                'age' => 35,
                'phone' => '0328-8901234',
                'marital_status' => 'married',
                'present_address' => 'House 78, Bahria Town, Lahore',
                'permanent_address' => 'House 78, Bahria Town, Lahore',
                'emergency_name' => 'Hassan Ali',
                'emergency_phone' => '0328-8901235',
                'emergency_relation' => 'Husband',
            ],
            [
                'name' => 'Bilal Khan',
                'gender' => 'male',
                'age' => 19,
                'phone' => '0329-9012345',
                'marital_status' => 'single',
                'present_address' => 'House 34, G-10, Islamabad',
                'permanent_address' => 'House 34, G-10, Islamabad',
                'emergency_name' => 'Amina Khan',
                'emergency_phone' => '0329-9012346',
                'emergency_relation' => 'Mother',
            ],
            [
                'name' => 'Hira Siddiqui',
                'gender' => 'female',
                'age' => 42,
                'phone' => '0330-0123456',
                'marital_status' => 'married',
                'present_address' => 'Flat 56, Gulshan-e-Iqbal, Karachi',
                'permanent_address' => 'Flat 56, Gulshan-e-Iqbal, Karachi',
                'emergency_name' => 'Ali Siddiqui',
                'emergency_phone' => '0330-0123457',
                'emergency_relation' => 'Husband',
            ],
            [
                'name' => 'Usman Iqbal',
                'gender' => 'male',
                'age' => 51,
                'phone' => '0331-1234567',
                'marital_status' => 'married',
                'present_address' => 'House 90, Wapda Town, Lahore',
                'permanent_address' => 'House 90, Wapda Town, Lahore',
                'emergency_name' => 'Sana Iqbal',
                'emergency_phone' => '0331-1234568',
                'emergency_relation' => 'Wife',
            ],
            [
                'name' => 'Zara Ahmed',
                'gender' => 'female',
                'age' => 15,
                'phone' => '0332-2345678',
                'marital_status' => 'single',
                'present_address' => 'House 23, DHA Phase 6, Karachi',
                'permanent_address' => 'House 23, DHA Phase 6, Karachi',
                'emergency_name' => 'Saima Ahmed',
                'emergency_phone' => '0332-2345679',
                'emergency_relation' => 'Mother',
            ],
            [
                'name' => 'Kamran Ali',
                'gender' => 'male',
                'age' => 38,
                'phone' => '0333-3456789',
                'marital_status' => 'married',
                'present_address' => 'House 67, Cavalry Ground, Lahore',
                'permanent_address' => 'House 67, Cavalry Ground, Lahore',
                'emergency_name' => 'Hina Ali',
                'emergency_phone' => '0333-3456790',
                'emergency_relation' => 'Wife',
            ],
            [
                'name' => 'Nida Malik',
                'gender' => 'female',
                'age' => 29,
                'phone' => '0334-4567890',
                'marital_status' => 'single',
                'present_address' => 'Flat 12, E-11, Islamabad',
                'permanent_address' => 'Flat 12, E-11, Islamabad',
                'emergency_name' => 'Tariq Malik',
                'emergency_phone' => '0334-4567891',
                'emergency_relation' => 'Father',
            ],
            [
                'name' => 'Fahad Hassan',
                'gender' => 'male',
                'age' => 47,
                'phone' => '0335-5678901',
                'marital_status' => 'married',
                'present_address' => 'House 45, Garden Town, Lahore',
                'permanent_address' => 'House 45, Garden Town, Lahore',
                'emergency_name' => 'Rabia Hassan',
                'emergency_phone' => '0335-5678902',
                'emergency_relation' => 'Wife',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }
    }
}
